---
name: Terraform Plan and Apply

on:
  workflow_dispatch:
    inputs:
      subdirectory:
        default: ''
        type: string
      working_directory:
        default: ''
        type: string
      aws_region:
        default: ap-south-1
        type: string
      environment:
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod  

jobs:
  terraform:
    uses: KarthikKunchala23/gp-github-workflows/.github/workflows/terraform.yaml@main
    permissions:
      id-token: write
      contents: read

    with:
      working_directory: ${{ github.event.inputs.subdirectory != '' && format('terraform/{0}', github.event.inputs.subdirectory) || 'terraform' }}
      aws_region: ${{ github.event.inputs.aws_region || 'ap-south-1' }}
      environment: ${{ github.event.inputs.environment || 'dev' }}
